### ISSUE TITLE
can someone help me configure an api?

### ISSUE THREAD

**Issue by overkido** [Sky-CSC/OSL#11]
I have this error in the api in the ex of the OSL-client, since the OSL-WEB runs completely without errors, could someone help me solve this?, I already configured and reconfigured everything 3 times and I cannot run it anymore.

**Comment by Sky-CSC** [comment]
Hi @overkido 
Do you have an image or the error line ?

**Comment by overkido** [comment]
> Hi @overkido Do you have an image or the error line ?

![image](https://github.com/Sky-CSC/OSL/assets/89580284/1ffb1b3e-50e0-44da-9eb0-a146cb48b688)

**Comment by Sky-CSC** [comment]
I see you're using V1.0.0, you should download the latest version v1.1.0, it fixes this error.
[Link last version](https://github.com/Sky-CSC/OSL/releases/tag/v1.1.0)

**Comment by overkido** [comment]
I put v1.1 but the problem continues.
![image](https://github.com/Sky-CSC/OSL/assets/89580284/04602c04-0802-4461-9ba6-a20b9687e2f1)
![image](https://github.com/Sky-CSC/OSL/assets/89580284/4d8f4e3b-f18c-4536-9b5c-cca17169a0b5)

**Comment by Sky-CSC** [comment]
What is the IP address of the PC on which you launched OSL-Web?

**Comment by Sky-CSC** [comment]
Apparently it's the DNS resolution that's having a problem.
What is the result of the "ipconfig" command in cmd ?

**Comment by overkido** [comment]
> Apparently it's the DNS resolution that's having a problem. What is the result of the "ipconfig" command in cmd ?

![image](https://github.com/Sky-CSC/OSL/assets/89580284/5bba9eca-c6c5-4d80-890b-659ba3312209)

**Comment by Sky-CSC** [comment]
For view 4 it's normal, it's only active during the 3min timer of the champ select when you're in spectator mode (at the end).
The whole inGame part is under development, there's only an overlay to display teams/scores/..., no display of score like tower, kill, items, level, ... for the moment.
But V1.2.0, when released, will have these features (expected late June - early July).

If you say that the champ select works, does that mean that OSL-client and OSL-Web communicate well ? Do you have the display of banns and picks ?

**Comment by overkido** [comment]
> If you say that the champ select works, does that mean that OSL-client and OSL-Web communicate well ? Do you have the display of banns and picks ?

I solved the problem I think kkkk, I solved it by modifying the ip as you said, I put the same ip that opens in OSL Web, as you can see in the image below OSL Web it searches the IP alone here no hey why, I put the ip of the machine and it gave an error so I left the ip that it opens alone and put the same ip in the Client and the error stopped.

![image](https://github.com/Sky-CSC/OSL/assets/89580284/1bb1e40c-54b9-4efb-bddb-b0a564f7b710)
![image](https://github.com/Sky-CSC/OSL/assets/89580284/4ccd4483-50fe-41af-8374-b09b6a59fb7c)

**Comment by overkido** [comment]
view 4 error in picks and bans is this one
![image](https://github.com/Sky-CSC/OSL/assets/89580284/52111f9e-5f59-40dc-8b99-e54bd19bc633)

**Comment by Sky-CSC** [comment]
This display only works when you're watching the champ select.
When players start their game and the champ select is finished, you have to wait 3 minutes before you can enter the game.
It's during this waiting phase that view 4 displays the following information.
As far as I'm concerned, view 4 displays information correctly when the field selection phase is in "Game_Starting" mode.
