### ISSUE TITLE
bug champion select

### ISSUE THREAD

**Issue by overkido** [Sky-CSC/OSL#25]
bug champion select, runes and post game, champions without image

![image](https://github.com/Sky-CSC/OSL/assets/89580284/ff5f3bc2-aac3-408d-8175-c0f8d116fa73)

**Comment by overkido** [comment]
I adjusted the images, the language is in fr_fr, I wanted to put it in pt_br, but because in fr_fr I couldn't find the images folder, so I selected it in the panel's config tab
![image](https://github.com/Sky-CSC/OSL/assets/89580284/9244035b-edf0-4955-bf75-6619e7651804)

with pt_br it doesn't work so I left it in the fr_fr option without being the first option and pulled the images, since the post game I'm still configuring it but I wanted to translate it, how can I? where is the text for me to translate, editing the fonts model is not working either

![image](https://github.com/Sky-CSC/OSL/assets/89580284/65e813b1-3956-47a6-a83c-7a877739b69a)


![image](https://github.com/Sky-CSC/OSL/assets/89580284/0d571213-7647-445e-bfbc-2dc0e6ba9ae9)

**Comment by Sky-CSC** [comment]
Ok I see, the folder with the images must have a problem.
I'll try to find out why it's not working.

For the translation I forgot to put a custom field, I'll have a patch made to fix that.

**Comment by Sky-CSC** [comment]
The file are fixed and custom win lose add in [v1.1.7](https://github.com/Sky-CSC/OSL/releases/latest)
