### ISSUE TITLE
hm... not working

### ISSUE THREAD

**Issue by shinilee** [Sky-CSC/OSL#6]
Getting Started
there is mistypo I think

3. Run OSL-Client on the computer
4. Run OSL-Client on the computer

I run server and client on same pc and I did edit appsettings.json file to http://0.0.0.0:4141
I run OSL-Server.exe, OSL-Client.exe in same pc and when I test to run with league client
made custom game and and it read lobby but once I start the OSL-Client.exe cmd closed

**Comment by shinilee** [comment]
Edit

I didn't put my own ip address so the cmd is not closing but I'm still having problem try to work it out
view1,2,3,4 it said disabled

info champ select view 3 is disabled

**Comment by Sky-CSC** [comment]
A new version will be released soon that will fix these problems.
Probably before the end of next week.
